openapi: 3.0.1
info:
  title: Expenditure Tracker API
  description: Expenditure Tracker API
  version: 1.0.0
servers:
  - url: localhost:6002/api/v1
components:
  securitySchemes:
    bearerAuth: 
      type: "apiKey"
      description: |
        Bearer \<token\>
        <br/>OR<br/>
      name: "authorization"
      scheme: "bearer"
      in: "header"
paths:
  /users/login/:
    post:
      tags:
        - "Auth"
      summary: "Login User"
      operationId: "LoginUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
  /users/register/:
    post:
      tags:
        - "Auth"
      summary: "Register User"
      operationId: "RegsiterUser"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - fullName
                - email
                - password
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
  /groups:
    post:
      tags:
        - "Group"
      summary: "Create Group"
      operationId: "CreateGroup"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - name: authorization 
          in: header
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    get:
      tags:
        - "Group"
      summary: "Fetch Group List with pagination"
      operationId: "group-list"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - in: header
          name: authorization 
          required: true 
          schema: 
            type: string
        - name: page
          in: query
          schema: 
            type: number
        - name: limit
          in: query
          schema: 
            type: number
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"    
  "/groups/{groupId}/":
    get:
      tags:
        - "Group"
      summary: "Fetch Group detail based on ID"
      operationId: "group-detail"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization 
          required: true 
          schema: 
            type: string
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    delete:
      tags:
        - "Group"
      summary: "delete group name based on ID"
      operationId: "delete-group"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization  
          required: true
          schema: 
            type: string
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
  /groups/join-group:
    post:
      tags:
        - "Group"
      summary: "Join Group"
      operationId: "join-group"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - name: authorization 
          in: header
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupId:
                  type: string
              required:
                - groupId
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"

  /items:
    post:
      tags:
        - "Item"
      summary: "Create Item"
      operationId: "create-item"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - name: authorization 
          in: header
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                unit:
                  type: string
                groupId:
                  type: string
              required:
                - name
                - unit
                - groupId
      responses:
        "201":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    get:
      tags:
        - "Item"
      summary: "Fetch Item List"
      operationId: "item-list"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - in: header
          name: authorization 
          required: true 
          schema: 
            type: string
        - name: groupId
          in: query
          schema: 
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"    
  "/items/{itemId}/":
    get:
      tags:
        - "Item"
      summary: "Fetch item detail based on ID"
      operationId: "item-detail"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization 
          required: true 
          schema: 
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    post:
      tags:
        - "Item"
      summary: "update item details based on ID"
      operationId: "update-item"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization  
          required: true
          schema: 
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                unit:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    delete:
      tags:
        - "Item"
      summary: "delete item based on ID"
      operationId: "delete-item"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization  
          required: true
          schema: 
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
  /purchase-item:
    post:
      tags:
        - "Purchase Item"
      summary: "Create purchase Item"
      operationId: "create-purchase-item"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - name: authorization 
          in: header
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                purchaseDate:
                  type: string
                purchaseItem:
                  type: string
                units:
                  type: string
                totalCost:
                  type: string
                billAvailable:
                  type: boolean
                groupId:
                  type: string
              required:
                - purchaseDate
                - purchaseItem
                - units
                - totalCost
                - billAvailable
                - groupId
      responses:
        "201":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    get:
      tags:
        - "Purchase Item"
      summary: "Fetch purchase Item List"
      operationId: "purchase-item-list"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters:
        - in: header
          name: authorization 
          required: true 
          schema: 
            type: string
        - name: groupId
          in: query
          schema: 
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found" 
  "/purchase-item/{itemId}/":
    get:
      tags:
        - "Purchase Item"
      summary: "Fetch purchase item detail based on ID"
      operationId: "purchase-item-detail"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization 
          required: true 
          schema: 
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    post:
      tags:
        - "Purchase Item"
      summary: "update purchase item details based on ID"
      operationId: "update-purchase-item"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization  
          required: true
          schema: 
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                purchaseDate:
                  type: string
                purchaseItem:
                  type: string
                units:
                  type: string
                totalCost:
                  type: string
                billAvailable:
                  type: string
                groupId:
                  type: string                
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"
    delete:
      tags:
        - "Purchase Item"
      summary: "delete purchase item based on ID"
      operationId: "delete-purchase-item"
      security:
        - bearerAuth:
          type: "http"
          scheme: "bearer"
      parameters: 
        - in: header
          name: authorization  
          required: true
          schema: 
            type: string
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: "Invalid"
        "404":
          description: "Not Found"